services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - cnc-killer-network

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - cnc-killer-vol-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: Asia/Bangkok
    ports:
      - "${EXTERNAL_DB_PORT}:5432"
    networks:
      - cnc-killer-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    volumes:
      - cnc-killer-vol-pgadmin:/var/lib/pgadmin
    networks:
      - cnc-killer-network
volumes:
  cnc-killer-vol-db:
    driver: local
  cnc-killer-vol-pgadmin:
    driver: local
networks:
  cnc-killer-network: